### ISSUE TITLE
No Zone, No Device ID,  Cannot reset Macro Channel, and Prepare zone failed.

### ISSUE THREAD

**Issue by alokchy04** [Thinxtra/Xkit-Sample#4]
Hi, I got a Xkit in Brisbane. I uploaded this code in my device but after that, it stopped working. It can not identify zone and device id anymore. Please check the attached screenshot. Please fix this issue or let me know if I missed any important points. 

Kind regards
Alok Kumar Chowdhury
alok.chowdhury@qut.edu.au

<img width="320" alt="screenshot 2017-06-02 17 06 42" src="https://cloud.githubusercontent.com/assets/25377043/26714842/9c847a00-47b6-11e7-9e87-e83b40978f73.png">

**Comment by devlware** [comment]
Did you find the problem @alokchy04?

**Comment by alokchy04** [comment]
Thanks a lot for following up. It has been fixed. The problem was solved automatically after some time.
Kind regards Alok
		

		Get Outlook for iOS
	





On Sat, Jun 3, 2017 at 12:15 AM +1000, "Diego W. Antunes" <notifications@github.com> wrote:












Did you find the problem @alokchy04?
